import { TimeNames } from "./types";
import colors from "tailwindcss/colors";

export const HOUR_FORMAT = "HH:mm";
export const HOUR_FORMAT_12 = "h:mm a";
export const API_DATE_FORMAT = "dd.MM.yyyy";

export const LOCAL_KEYS = {
  Settings: "VAKITLER_SETTINGS",
  Data: "VAKITLER_DATA",
  Lang: "VAKITLER_LANG",
  UpdateDate: "VAKITLER_UPDATE_DATE",
  FeedbackModal: "VAKITLER_FEEDBACK_MODAL",
};

export enum Phease {
  ictima = 0,
  ruyet = 1,
  r1 = 2,
  r2 = 3,
  r3 = 4,
  r4 = 5,
  r5 = 6,
  ilkdordun = 7,
  i1 = 8,
  i2 = 9,
  i3 = 10,
  i4 = 11,
  i5 = 12,
  i6 = 13,
  i7 = 14,
  dolunay = 15,
  d1 = 16,
  d2 = 17,
  d3 = 18,
  d4 = 19,
  d5 = 20,
  d6 = 21,
  d7 = 22,
  sondordun = 23,
  sd1 = 24,
  sd2 = 25,
  sd3 = 26,
  sd4 = 27,
  sd5 = 28,
  sd6 = 29,
}

export const CSSVariables: Record<TimeNames, Record<string, string>> = {
  [TimeNames.Imsak]: {
    "--primary": colors.indigo[900],
    "--secondary": colors.indigo[50],
    "--gradient-to": colors.indigo[950],
    "--gradient-via": colors.indigo[700],
    "--gradient-from": colors.sky[600],
    "--moon-light": colors.orange[50],
    "--moon-dark": colors.indigo[950],
    "--card-bg": "rgba(23, 37, 84,0.2)",
    "--card-text": "var(--primary)",
  },
  [TimeNames.Gunes]: {
    "--primary": colors.blue[50],
    "--secondary": colors.blue[900],
    "--gradient-to": colors.blue[600],
    "--gradient-via": colors.blue[300],
    "--gradient-from": colors.orange[100],
    "--moon-light": colors.blue[50],
    "--moon-dark": colors.blue[400],
    "--card-bg": "rgba(23, 37, 84,0.1)",
    "--card-text": "var(--secondary)",
  },
  [TimeNames.Ogle]: {
    "--primary": colors.blue[50],
    "--secondary": colors.blue[900],
    "--gradient-to": colors.blue[500],
    "--gradient-via": colors.blue[300],
    "--gradient-from": colors.yellow[50],
    "--moon-light": colors.white,
    "--moon-dark": colors.blue[300],
    "--card-bg": "rgba(23, 37, 84,0.1)",
    "--card-text": "var(--secondary)",
  },
  [TimeNames.Ikindi]: {
    "--primary": colors.blue[50],
    "--secondary": colors.blue[900],
    "--gradient-to": colors.blue[500],
    "--gradient-via": colors.indigo[200],
    "--gradient-from": colors.orange[200],
    "--moon-light": colors.white,
    "--moon-dark": colors.blue[300],
    "--card-bg": "rgba(23, 37, 84,0.1)",
    "--card-text": "var(--secondary)",
  },
  [TimeNames.Aksam]: {
    "--primary": colors.blue[900],
    "--secondary": colors.blue[50],
    "--gradient-to": colors.indigo[950],
    "--gradient-via": colors.indigo[700],
    "--gradient-from": colors.sky[600],
    "--moon-light": colors.blue[50],
    "--moon-dark": colors.indigo[900],
    "--card-bg": "rgba(23, 37, 84,0.2)",
    "--card-text": "var(--primary)",
  },
  [TimeNames.Yatsi]: {
    "--primary": colors.blue[900],
    "--secondary": colors.blue[50],
    "--gradient-to": colors.black,
    "--gradient-via": colors.indigo[900],
    "--gradient-from": colors.blue[900],
    "--moon-light": colors.indigo[50],
    "--moon-dark": colors.indigo[950],
    "--card-bg": "rgba(255, 255, 255,0.1)",
    "--card-text": "var(--primary)",
  },
};
